#!/usr/bin/env python3
"""
Generate 30 individual job scripts for Tier 1 Experiment 1.2: MNIST Classification
6 models × 5 seeds = 30 jobs
"""

from pathlib import Path

# Configuration
MODELS = [
    'quantum_hydra',
    'quantum_hydra_hybrid',
    'quantum_mamba',
    'quantum_mamba_hybrid',
    'classical_hydra',
    'classical_mamba'
]

SEEDS = [2024, 2025, 2026, 2027, 2028]

# Hyperparameters - Option 1 Modified (balanced speed/quality)
N_QUBITS = 6
QLCU_LAYERS = 2
D_MODEL = 128
D_STATE = 16
N_EPOCHS = 50          # Keep 50 epochs for convergence
BATCH_SIZE = 32        # Increased to 32 for faster training
LEARNING_RATE = 1e-3
N_TRAIN = 500          # Reduced from 1000 (50 samples/class - good statistical power)
N_VALTEST = 250        # Reduced from 500
EARLY_STOPPING = 10    # Stop if no improvement for 10 epochs

OUTPUT_DIR = "./experiments/mnist_results"
CONDA_ENV = "qhydra"  # micromamba environment name
MICROMAMBA_PATH = "/home/connectome/mandy/.local/bin/micromamba"  # Full path to micromamba

def create_job_script(model_name, seed, job_id):
    """Create a single job script for (model, seed) pair."""

    script_content = f"""#!/bin/bash
#SBATCH --job-name=mnist_{model_name}_s{seed}
#SBATCH --account=m4138_g
#SBATCH --constraint=gpu&hbm80g
#SBATCH --qos=shared
#SBATCH -t 48:00:00
#SBATCH --nodes=1
#SBATCH --gpus=1
#SBATCH --cpus-per-task=32
#SBATCH --output={OUTPUT_DIR}/logs/mnist_{model_name}_seed{seed}.log
#SBATCH --error={OUTPUT_DIR}/logs/mnist_{model_name}_seed{seed}.log

# Job script for MNIST Classification: {model_name} (seed={seed})
# Auto-generated by generate_mnist_job_scripts.py

# Activate micromamba environment
eval "$({MICROMAMBA_PATH} shell hook --shell bash)"
{MICROMAMBA_PATH} activate {CONDA_ENV}

# Run training
python scripts/training/run_single_model_mnist.py \\
    --model-name {model_name} \\
    --n-qubits {N_QUBITS} \\
    --qlcu-layers {QLCU_LAYERS} \\
    --d-model {D_MODEL} \\
    --d-state {D_STATE} \\
    --n-epochs {N_EPOCHS} \\
    --batch-size {BATCH_SIZE} \\
    --lr {LEARNING_RATE} \\
    --n-train {N_TRAIN} \\
    --n-valtest {N_VALTEST} \\
    --early-stopping-patience {EARLY_STOPPING} \\
    --seed {seed} \\
    --output-dir {OUTPUT_DIR} \\
    --device cuda

echo "Job completed: {model_name} seed={seed}"
"""

    return script_content


def main():
    """Generate all 30 job scripts."""

    # Create job scripts directory
    jobs_dir = Path("./job_scripts/image")
    jobs_dir.mkdir(parents=True, exist_ok=True)

    print("="*80)
    print("Generating MNIST Classification Job Scripts")
    print("="*80)
    print(f"Models: {len(MODELS)}")
    print(f"Seeds: {len(SEEDS)}")
    print(f"Total jobs: {len(MODELS) * len(SEEDS)}")
    print(f"Output directory: {jobs_dir}")
    print(f"Micromamba environment: {CONDA_ENV}")
    print("="*80)

    job_files = []
    job_id = 1

    for model_name in MODELS:
        for seed in SEEDS:
            # Create job script
            script_content = create_job_script(model_name, seed, job_id)

            # Save to file
            job_filename = f"mnist_{model_name}_seed{seed}.sh"
            job_path = jobs_dir / job_filename

            with open(job_path, 'w') as f:
                f.write(script_content)

            # Make executable
            job_path.chmod(0o755)

            job_files.append(job_filename)
            print(f"[{job_id:2d}/30] Created: {job_filename}")
            job_id += 1

    print("\n" + "="*80)
    print("Job Scripts Generation Complete!")
    print("="*80)

    # Create master submission script
    master_script = """#!/bin/bash
# Master submission script for all 30 MNIST classification jobs
# Run all jobs in parallel (if you have GPU resources)
# Or submit in batches

echo "Submitting 30 MNIST classification jobs..."
echo "================================================"

"""

    for i, job_file in enumerate(job_files, 1):
        master_script += f"# Job {i}: {job_file}\n"
        master_script += f"sbatch job_scripts/image/{job_file}\n"
        master_script += f"echo \"Submitted: {job_file}\"\n\n"

        # Add pause every 6 jobs (one per model) to avoid overwhelming the SLURM queue
        if i % 6 == 0 and i < len(job_files):
            master_script += f"# Pause to avoid overwhelming SLURM queue\n"
            master_script += f"echo \"Pausing for 2 seconds...\"\n"
            master_script += f"sleep 2\n\n"

    master_script += """
echo "================================================"
echo "All jobs submitted!"
echo "Monitor progress with: tail -f experiments/mnist_results/logs/*.log"
echo "Or check individual logs in: experiments/mnist_results/logs/"
"""

    master_path = jobs_dir / "submit_all_mnist_jobs.sh"
    with open(master_path, 'w') as f:
        f.write(master_script)
    master_path.chmod(0o755)

    print(f"\nMaster submission script created: {master_path}")

    # Create logs directory
    logs_dir = Path(OUTPUT_DIR) / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    print(f"Logs directory created: {logs_dir}")

    print("\n" + "="*80)
    print("Usage Instructions:")
    print("="*80)
    print("1. Submit all jobs in parallel:")
    print(f"   bash {master_path}")
    print()
    print("2. Submit individual jobs:")
    print(f"   bash job_scripts/image/mnist_quantum_hydra_seed2024.sh")
    print()
    print("3. Monitor progress:")
    print(f"   tail -f experiments/mnist_results/logs/*.log")
    print()
    print("4. After completion, aggregate results:")
    print(f"   python scripts/aggregation/aggregate_mnist_results.py")
    print("="*80)


if __name__ == "__main__":
    main()
