#!/usr/bin/env python3
"""
Generate 30 individual job scripts for Tier 1 Experiment 1.3: DNA Sequence Classification
6 models × 5 seeds = 30 jobs
"""

from pathlib import Path
import sys

# Add parent directory to path to import config
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from config import (
    PROJECT_ROOT,
    PY,
    get_output_dir,
    get_jobs_dir,
    get_script_path,
    get_slurm_config,
)

# Configuration
MODELS = [
    'quantum_hydra',
    'quantum_hydra_hybrid',
    'quantum_mamba',
    'quantum_mamba_hybrid',
    'classical_hydra',
    'classical_mamba'
]

SEEDS = [2024, 2025, 2026, 2027, 2028]

# Hyperparameters from EXPERIMENTAL_PLAN_README.md (lines 468-478)
N_QUBITS = 6
QLCU_LAYERS = 2
D_MODEL = 128
D_STATE = 16
N_EPOCHS = 50
BATCH_SIZE = 32  # Updated for faster training
LEARNING_RATE = 1e-3
EARLY_STOPPING = 10  # Early stopping patience
N_TRAIN = 100  # DNA dataset has only 106 total sequences
N_VALTEST = 50
ENCODING = 'onehot'  # DNA encoding method

# Paths (from config)
OUTPUT_DIR = get_output_dir('dna')
JOBS_DIR = get_jobs_dir('dna')

# SLURM Configuration (from config, can be overridden)
slurm_config = get_slurm_config(time='48:00:00')  # DNA needs longer time
SLURM_ACCOUNT = slurm_config['account']
SLURM_CONSTRAINT = slurm_config['constraint']
SLURM_QOS = slurm_config['qos']
SLURM_TIME = slurm_config['time']
SLURM_NODES = slurm_config['nodes']
SLURM_GPUS = slurm_config['gpus']
SLURM_CPUS = slurm_config['cpus_per_task']

def create_job_script(model_name, seed, job_id):
    """Create a single job script for (model, seed) pair."""

    script_content = f"""#!/bin/bash
#SBATCH --job-name=dna_{model_name}_s{seed}
#SBATCH --account={SLURM_ACCOUNT}
#SBATCH --constraint={SLURM_CONSTRAINT}
#SBATCH --qos={SLURM_QOS}
#SBATCH -t {SLURM_TIME}
#SBATCH --nodes={SLURM_NODES}
#SBATCH --gpus={SLURM_GPUS}
#SBATCH --cpus-per-task={SLURM_CPUS}
#SBATCH --output={str(OUTPUT_DIR)}/logs/dna_{model_name}_seed{seed}.log
#SBATCH --error={str(OUTPUT_DIR)}/logs/dna_{model_name}_seed{seed}.log

# Job script for DNA Sequence Classification: {model_name} (seed={seed})
# Auto-generated by generate_dna_job_scripts.py

# Use Python directly from environment
PYTHON_CMD="{PY}"

# Navigate to project root
cd {str(PROJECT_ROOT)}

# Run training
$PYTHON_CMD {str(get_script_path('run_single_model_dna.py'))} \\
    --model-name {model_name} \\
    --n-qubits {N_QUBITS} \\
    --qlcu-layers {QLCU_LAYERS} \\
    --d-model {D_MODEL} \\
    --d-state {D_STATE} \\
    --n-epochs {N_EPOCHS} \\
    --batch-size {BATCH_SIZE} \\
    --lr {LEARNING_RATE} \\
    --early-stopping-patience {EARLY_STOPPING} \\
    --n-train {N_TRAIN} \\
    --n-valtest {N_VALTEST} \\
    --encoding {ENCODING} \\
    --seed {seed} \\
    --output-dir {str(OUTPUT_DIR)} \\
    --device cuda

echo "Job completed: {model_name} seed={seed}"
"""

    return script_content


def main():
    """Generate all 30 job scripts."""

    # Create job scripts directory
    jobs_dir = JOBS_DIR
    jobs_dir.mkdir(parents=True, exist_ok=True)

    print("="*80)
    print("Generating DNA Sequence Classification Job Scripts")
    print("="*80)
    print(f"Models: {len(MODELS)}")
    print(f"Seeds: {len(SEEDS)}")
    print(f"Total jobs: {len(MODELS) * len(SEEDS)}")
    print(f"Output directory: {jobs_dir}")
    print(f"Python: {PY}")
    print(f"Encoding: {ENCODING}")
    print("="*80)

    job_files = []
    job_id = 1

    for model_name in MODELS:
        for seed in SEEDS:
            # Create job script
            script_content = create_job_script(model_name, seed, job_id)

            # Save to file
            job_filename = f"dna_{model_name}_seed{seed}.sh"
            job_path = jobs_dir / job_filename

            with open(job_path, 'w') as f:
                f.write(script_content)

            # Make executable
            job_path.chmod(0o755)

            job_files.append(job_filename)
            print(f"[{job_id:2d}/30] Created: {job_filename}")
            job_id += 1

    print("\n" + "="*80)
    print("Job Scripts Generation Complete!")
    print("="*80)

    # Create master submission script
    master_script = """#!/bin/bash
# Master submission script for all 30 DNA sequence classification jobs
# Run all jobs in parallel (if you have GPU resources)
# Or submit in batches

echo "Submitting 30 DNA sequence classification jobs..."
echo "================================================"

"""

    for i, job_file in enumerate(job_files, 1):
        master_script += f"# Job {i}: {job_file}\n"
        master_script += f"sbatch {str(jobs_dir)}/{job_file}\n"
        master_script += f"echo \"Submitted: {job_file}\"\n\n"

        # Add pause every 6 jobs (one per model) to avoid overwhelming the SLURM queue
        if i % 6 == 0 and i < len(job_files):
            master_script += f"# Pause to avoid overwhelming SLURM queue\n"
            master_script += f"echo \"Pausing for 2 seconds...\"\n"
            master_script += f"sleep 2\n\n"

    master_script += """
echo "================================================"
echo "All jobs submitted!"
echo "Monitor progress with: tail -f experiments/dna_results/logs/*.log"
echo "Or check individual logs in: experiments/dna_results/logs/"
"""

    master_path = jobs_dir / "submit_all_dna_jobs.sh"
    with open(master_path, 'w') as f:
        f.write(master_script)
    master_path.chmod(0o755)

    print(f"\nMaster submission script created: {master_path}")

    # Create logs directory
    logs_dir = OUTPUT_DIR / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)
    print(f"Logs directory created: {logs_dir}")

    print("\n" + "="*80)
    print("Usage Instructions:")
    print("="*80)
    print("1. Submit all jobs in parallel:")
    print(f"   bash {master_path}")
    print()
    print("2. Submit individual jobs:")
    print(f"   bash {str(jobs_dir)}/dna_quantum_hydra_seed2024.sh")
    print()
    print("3. Monitor progress:")
    print(f"   tail -f {str(OUTPUT_DIR)}/logs/*.log")
    print()
    print("4. After completion, aggregate results:")
    print(f"   python scripts/aggregation/aggregate_dna_results.py")
    print("="*80)


if __name__ == "__main__":
    main()
